### PR TITLE
implemented progress bar in student member status

### PR DESCRIPTION
**Pull request by aniarya82**
screen shot 2015-08-30 at 8 40 55 pm

### CODE REVIEW

**Comment by icyflame** [comment]
@aniarya82 The screenshot doesn't make sense.

How does this improve the status screen?

**Comment by aniarya82** [comment]
Arey i have implemented bootstrap's stacked progress bar.
This will enable us to view the status more qualitatively.

**Comment by icyflame** [comment]
@aniarya82 Can you provide a screenshot that describes exactly how this may actually look like?

**Comment by aniarya82** [comment]
Like one student member got 35 alumni and his tobesearched is 17 ready is 9 and found is 9, so the complete progress bar would be in 3 stacks where 17 parts are info 9 parts are primary and 9 parts are success and no danger reprinting none dropped till yet.

I would be like the code bar in top of github repo representing html/css: 89% and javascript: 9%, something like that.

**Comment by icyflame** [comment]
Mind uploading a screenshot that shows all of the above stuff?

On 30 August 2015 at 22:16, Hiten Chowdhary notifications@github.com
wrote:

> Like one student member got 35 alumni and his tobesearched is 17 ready is
> 9 and found is 9, so the complete progress bar would be in 3 stacks where
> 17 parts are info 9 parts are primary and 9 parts are success and no danger
> reprinting none dropped till yet.
> 
> I would be like the code bar in top of github repo representing html/css:
> 89% and javascript: 9%, something like that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icyflame/erp-rails/pull/79#issuecomment-136159361.

## 

Best Regards,

Siddharth Kannan,
Third Year, Mechanical Engineering Department,
Indian Institute of Technology,
Kharagpur,
West Bengal, India.
+91 9800190996.

**Comment by aniarya82** [comment]
screen shot 2015-08-30 at 11 52 41 pm

I was planning something like this.

**Comment by icyflame** [comment]
I would prefer it if alongwith the percentages and the colors, there is
also a number of alumni and the exact meaning of the color with every
status bar. It may seem repetitive but that is a better UX choice.

**Comment by aniarya82** [comment]
I think to represent the meaning of the color, we could implement tooltip.

**Comment by icyflame** [comment]
@aniarya82 

For now, let's put a hold on this feature. The present setup seems to serve well.

we can think about merging this later.

**Pull request closed without merging**
